---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Sheet 2-Table 1/Sheet 2-Table 1.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/2191/articles/190631/master/file/figures/Sheet%202-Table%201/Sheet%202-Table%201.csv"
    folder_url: "/users/2191/articles/190631/master/folder/figures/Sheet 2-Table 1"
    treatFirstLineAsHeader: true
